version: '3.5'

volumes:
  data:

services:
  database:
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm